<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'car' => '/Tests/classes/Car.php',
                'carcollection' => '/Tests/classes/CarCollection.php',
                'carproperties' => '/Tests/classes/CarProperties.php',
                'carproperty' => '/Tests/classes/CarProperty.php',
                'city' => '/Tests/classes/City.php',
                'client' => '/Tests/classes/Client.php',
                'collectiontest' => '/Tests/CollectionTest.php',
                'configparsertest' => '/Tests/ConfigParserTest.php',
                'configparsertestjson' => '/Tests/ConfigParserTestJSON.php',
                'country' => '/Tests/classes/Country.php',
                'dbtest' => '/Tests/DBTest.php',
                'dreamtable' => '/Tests/classes/DreamTable.php',
                'findertest' => '/Tests/FinderTest.php',
                'forsqltest' => '/Tests/classes/ForSQLTest.php',
                'jsontest' => '/Tests/JSONTest.php',
                'ludodb' => '/LudoDB.php',
                'ludodbcollection' => '/LudoDbCollection.php',
                'ludodbconfigparser' => '/LudoDbConfigParser.php',
                'ludodbiterator' => '/LudoDbIterator.php',
                'ludodbobject' => '/LudoDBObject.php',
                'ludodbtable' => '/LudoDbTable.php',
                'ludofinder' => '/LudoFinder.php',
                'ludosql' => '/LudoSQL.php',
                'person' => '/Tests/classes/Person.php',
                'personforconfigparser' => '/Tests/classes/PersonForConfigParser.php',
                'phone' => '/Tests/classes/Phone.php',
                'phonecollection' => '/Tests/classes/PhoneCollection.php',
                'sqltest' => '/Tests/SQLTest.php',
                'testbase' => '/Tests/TestBase.php',
                'testtable' => '/Tests/classes/TestTable.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd