<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'accessortest' => '/Tests/AccessorTest.php',
                'brand' => '/Tests/classes/Brand.php',
                'capital' => '/Tests/classes/JSONCaching/Capital.php',
                'capitals' => '/Tests/classes/JSONCaching/Capitals.php',
                'car' => '/Tests/classes/Car.php',
                'carcollection' => '/Tests/classes/CarCollection.php',
                'carproperties' => '/Tests/classes/CarProperties.php',
                'carproperty' => '/Tests/classes/CarProperty.php',
                'city' => '/Tests/classes/City.php',
                'client' => '/Tests/classes/Client.php',
                'collectiontest' => '/Tests/CollectionTest.php',
                'columnaliastest' => '/Tests/ColumnAliasTest.php',
                'configparsertest' => '/Tests/ConfigParserTest.php',
                'configparsertestjson' => '/Tests/ConfigParserTestJSON.php',
                'country' => '/Tests/classes/Country.php',
                'findertest' => '/Tests/FinderTest.php',
                'forsqltest' => '/Tests/classes/ForSQLTest.php',
                'jsontest' => '/Tests/JSONTest.php',
                'ludodb' => '/LudoDB.php',
                'ludodbcollection' => '/LudoDBCollection.php',
                'ludodbcollectionconfigparser' => '/LudoDBCollectionConfigParser.php',
                'ludodbconfigparser' => '/LudoDBConfigParser.php',
                'ludodbiterator' => '/LudoDBIterator.php',
                'ludodbjson' => '/LudoDBJSON.php',
                'ludodbmodel' => '/LudoDBModel.php',
                'ludodbmodeltests' => '/Tests/LudoDBTableTests.php',
                'ludodbobject' => '/LudoDBObject.php',
                'ludodbregistry' => '/LudoDBRegistry.php',
                'ludorequesthandler' => '/LudoRequestHandler.php',
                'ludosql' => '/LudoSQL.php',
                'manager' => '/Tests/classes/Manager.php',
                'mysqltests' => '/Tests/MysqlTests.php',
                'objectcreatortest' => '/Tests/ObjectCreatorTest.php',
                'people' => '/Tests/classes/People.php',
                'peopleplain' => '/Tests/classes/PeoplePlain.php',
                'performancetest' => '/Tests/PerformanceTest.php',
                'person' => '/Tests/classes/Person.php',
                'personforconfigparser' => '/Tests/classes/PersonForConfigParser.php',
                'phone' => '/Tests/classes/Phone.php',
                'phonecollection' => '/Tests/classes/PhoneCollection.php',
                'requesthandlertest' => '/Tests/RequestHandlerTest.php',
                'section' => '/Tests/classes/Section.php',
                'sqltest' => '/Tests/SQLTest.php',
                'testbase' => '/Tests/TestBase.php',
                'testgame' => '/Tests/classes/TestGame.php',
                'testtable' => '/Tests/classes/TestTable.php',
                'testtimer' => '/Tests/classes/TestTimer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd