<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'book' => '/examples/Book.php',
                'ludodb' => '/LudoDB.php',
                'ludodbadapter' => '/LudoDBInterfaces.php',
                'ludodbcache' => '/LudoDBCache.php',
                'ludodbclassnotfoundexception' => '/LudoDBExceptions.php',
                'ludodbcollection' => '/LudoDBCollection.php',
                'ludodbcollectionconfigparser' => '/LudoDBCollectionConfigParser.php',
                'ludodbconfigparser' => '/LudoDBConfigParser.php',
                'ludodbconnectionexception' => '/LudoDBExceptions.php',
                'ludodbexception' => '/LudoDBExceptions.php',
                'ludodbiterator' => '/LudoDBIterator.php',
                'ludodbmodel' => '/LudoDBModel.php',
                'ludodbmysql' => '/LudoDBMysql.php',
                'ludodbmysqli' => '/LudoDBMySqlI.php',
                'ludodbobject' => '/LudoDBObject.php',
                'ludodbobjectnotfoundexception' => '/LudoDBExceptions.php',
                'ludodbpdo' => '/LudoDBPDO.php',
                'ludodbregistry' => '/LudoDBRegistry.php',
                'ludodbrequesthandler' => '/LudoDBRequestHandler.php',
                'ludodbservice' => '/LudoDBInterfaces.php',
                'ludodbunauthorizedexception' => '/LudoDBExceptions.php',
                'ludosql' => '/LudoSQL.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd