<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'author' => '/../mod_rewrite/Author.php',
                'book' => '/../mod_rewrite/Book.php',
                'bookauthor' => '/../mod_rewrite/BookAuthor.php',
                'bookauthors' => '/../mod_rewrite/BookAuthors.php',
                'democities' => '/DemoCities.php',
                'democity' => '/DemoCity.php',
                'democountries' => '/DemoCountries.php',
                'democountry' => '/DemoCountry.php',
                'demostate' => '/DemoState.php',
                'demostates' => '/DemoStates.php',
                'ixhprofruns' => '/../../xhprof/xhprof_lib/utils/xhprof_runs.php',
                'ludodb' => '/../..//LudoDB.php',
                'ludodbadapter' => '/../..//LudoDBInterfaces.php',
                'ludodbcache' => '/../..//LudoDBCache.php',
                'ludodbclassnotfoundexception' => '/../..//LudoDBExceptions.php',
                'ludodbcollection' => '/../..//LudoDBCollection.php',
                'ludodbcollectionconfigparser' => '/../..//LudoDBCollectionConfigParser.php',
                'ludodbconfigparser' => '/../..//LudoDBConfigParser.php',
                'ludodbconnectionexception' => '/../..//LudoDBExceptions.php',
                'ludodbexception' => '/../..//LudoDBExceptions.php',
                'ludodbinvalidargumentsexception' => '/../..//LudoDBExceptions.php',
                'ludodbinvalidconfigexception' => '/../..//LudoDBExceptions.php',
                'ludodbinvalidserviceexception' => '/../..//LudoDBExceptions.php',
                'ludodbiterator' => '/../..//LudoDBIterator.php',
                'ludodbmodel' => '/../..//LudoDBModel.php',
                'ludodbmysql' => '/../..//LudoDBMysql.php',
                'ludodbmysqli' => '/../..//LudoDBMySqlI.php',
                'ludodbobject' => '/../..//LudoDBObject.php',
                'ludodbobjectnotfoundexception' => '/../..//LudoDBExceptions.php',
                'ludodbpdo' => '/../..//LudoDBPDO.php',
                'ludodbprofiling' => '/../..//LudoDBProfiling.php',
                'ludodbregistry' => '/../..//LudoDBRegistry.php',
                'ludodbrequesthandler' => '/../..//LudoDBRequestHandler.php',
                'ludodbservice' => '/../..//LudoDBInterfaces.php',
                'ludodbservicenotimplementedexception' => '/../..//LudoDBExceptions.php',
                'ludodbserviceregistry' => '/../..//LudoDBServiceRegistry.php',
                'ludodbsql' => '/../..//LudoDBSQL.php',
                'ludodbtreecollection' => '/../..//LudoDBTreeCollection.php',
                'ludodbunauthorizedexception' => '/../..//LudoDBExceptions.php',
                'ludodbutility' => '/../..//LudoDBUtility.php',
                'xhpprofiling' => '/../../xhprof/XHPProfiling.php',
                'xhprofruns_default' => '/../../xhprof/xhprof_lib/utils/xhprof_runs.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd